spring:
  profiles:
    active: dev
  freemarker:
#    cache: false
    request-context-attribute: request

# 分页
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

# Jwt相关配置
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: Bearer

# 限制上传文件大小配置
spring.http:
  multipart.maxFileSize: 524288000
  multipart.maxRequestSize: 524288000

file.maximum.upload.size: 5242880