#配置访问路径和端口
server:
  context-path: /ss
  port: 8081

spring:
  profiles.active: tomcat
  #Druid连接池配置信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://10.1.4.208:3306/social_security?characterEncoding=utf8&useSSL=true&allowMultiQueries=true
    #username: root
    #password: root!123
    
    url: jdbc:mysql://rm-8vbkn807437kx0jv6.mysql.zhangbei.rds.aliyuncs.com:3306/social_security?characterEncoding=utf8&useSSL=true&allowMultiQueries=true
    username: ywzc
    password: dianMi365
    
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 校验SQL，Oracle配置 spring.datasource.validationQuery: SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=truedruid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true